name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8  # Vous pouvez choisir une autre version de Python si nécessaire

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest  # Installe pytest pour les tests

    - name: Run tests
      run: |
        pytest test_MyCode.py --maxfail=1 --disable-warnings -q  # Exécute les tests du fichier test_MyCode.py

    - name: Upload test results to GitHub Actions
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: pytest-results
        path: ./test-results.xml  # Si vous générez des rapports de tests XML, vous pouvez spécifier le chemin ici
